#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Running pre-push checks..."

yarn build && \
npx tsc --noEmit && \
yarn lint && \
yarn test

if [ $? -ne 0 ]; then
  echo "❌ Pre-push checks failed. Fix errors before pushing."
  exit 1
fi

echo "✅ All pre-push checks passed!"
